const studentTypes = {
    CREATE_NEW_STUDENT_START:"CREATE_NEW_STUDENT_START",
    CREATE_NEW_STUDENT_ASYNC: "CREATE_NEW_STUDENT_ASYNC",
    CREATE_NEW_STUDENT_FAILURE:"CREATE_NEW_STUDENT_FAILURE",
    CREATE_NEW_STUDENT_SUCCESS: "CREATE_NEW_STUDENT_SUCCESS"
}

export default studentTypes;