export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_COURSE_VIEW = "SET_COURSE_VIEW";

export const ASYNC_REGISTERED_COURSES_START = "ASYNC_REGISTERED_COURSES_START";
export const ASYNC_REGISTERED_COURSES_SUCCESS =
  "ASYNC_REGISTERED_COURSES_SUCCESS";
export const ASYNC_REGISTERED_COURSES_FAILURE =
  "ASYNC_REGISTERED_COURSES_FAILURE";

export const ASYNC_UNREGISTERED_COURSES_START =
  "ASYNC_UNREGISTERED_COURSES_START";
export const ASYNC_UNREGISTERED_COURSES_SUCCESS =
  "ASYNC_UNREGISTERED_COURSES_SUCCESS";
export const ASYNC_UNREGISTERED_COURSES_FAILURE =
  "ASYNC_UNREGISTERED_COURSES_FAILURE";

export const ADD_COURSE_ATTENDANCE = "ADD_COURSE_ATTENDANCE";

export const LOGOUT = "LOGOUT";

export const USER_CREATED = "USER_CREATED";

export const RESET = "RESET";

export const USER_LOGOUT = "USER_LOGOUT";

export const attendanceTypes = {
  IS_LOADING_ATTENDANCE: "IS_LOADING_ATTENDANCE",
  ATTENDANCE_PROFILE_SUCCESS: "ATTENDANCE_PROFILE_SUCCESS",
  ATTENDANCE_PROFILE_FAILURE: "ATTENDANCE_PROFILE_FAILURE",
  IS_LOADING_COMMITS: "IS_LOADING_COMMITS",
  ATTENDANCE_COMMITS_FAILURE: "ATTENDANCE_COMMITS_FAILURE",
  ATTENDANCE_COMMITS_SUCCESS: "ATTENDANCE_COMMITS_SUCCESS",
  CLEAR_ATTENDANCE: "CLEAR_ATTENDANCE",
  ATT_PROFILES_SUCCESS: "ATT_PROFILES_SUCCESS",
  ATT_PROFILES_FAILURE: "ATT_PROFILES_FAILURE",
  IS_LOADING_ATT_PROFILES: "IS_LOADING_ATT_PROFILES"
};

export const commitedStudents = {
  IS_LOADING_COMMITED_STUDENTS: "IS_LOADING_COMMITED_STUDENTS",
  COMMITED_STUDENTS_SUCCESS: "COMMITED_STUDENTS_SUCCESS",
  COMMITED_STUDENTS_FAILURE: "COMMITED_STUDENTS_FAILURE"
}
