export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_COURSE_VIEW = "SET_COURSE_VIEW";

export const ASYNC_REGISTERED_COURSES_START= "ASYNC_REGISTERED_COURSES_START";
export const ASYNC_REGISTERED_COURSES_SUCCESS= "ASYNC_REGISTERED_COURSES_SUCCESS";
export const ASYNC_REGISTERED_COURSES_FAILURE= "ASYNC_REGISTERED_COURSES_FAILURE";

export const ASYNC_UNREGISTERED_COURSES_START= "ASYNC_UNREGISTERED_COURSES_START";
export const ASYNC_UNREGISTERED_COURSES_SUCCESS= "ASYNC_UNREGISTERED_COURSES_SUCCESS";
export const ASYNC_UNREGISTERED_COURSES_FAILURE= "ASYNC_UNREGISTERED_COURSES_FAILURE";

export const LOGOUT = "LOGOUT";