export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_COURSE_VIEW = "SET_COURSE_VIEW";

export const ASYNC_REGISTERED_COURSES_START = "ASYNC_REGISTERED_COURSES_START";
export const ASYNC_REGISTERED_COURSES_SUCCESS =
  "ASYNC_REGISTERED_COURSES_SUCCESS";
export const ASYNC_REGISTERED_COURSES_FAILURE =
  "ASYNC_REGISTERED_COURSES_FAILURE";

export const ASYNC_UNREGISTERED_COURSES_START =
  "ASYNC_UNREGISTERED_COURSES_START";
export const ASYNC_UNREGISTERED_COURSES_SUCCESS =
  "ASYNC_UNREGISTERED_COURSES_SUCCESS";
export const ASYNC_UNREGISTERED_COURSES_FAILURE =
  "ASYNC_UNREGISTERED_COURSES_FAILURE";

export const ADD_COURSE_ATTENDANCE = "ADD_COURSE_ATTENDANCE";

export const LOGOUT = "LOGOUT";

export const USER_CREATED = "USER_CREATED";

export const RESET = "RESET";

export const attendanceTypes = {
  IS_LOADING_ATTENDANCE: "IS_LOADING_ATTENDANCE",
  ATTENDANCE_PROFILE_SUCCESS: "ATTENDANCE_PROFILE_SUCCESS",
  ATTENDANCE_PROFILE_FAILURE: "ATTENDANCE_PROFILE_SUCCESS",
  IS_LOADING_COMMITS: "IS_LOADING_COMMITS",
  ATTENDANCE_COMMITS_FAILURE: "ATTENDANCE_COMMITS_FAILURE",
  ATTENDANCE_COMMITS_SUCCESS: "ATTENDANCE_COMMITS_SUCCESS",
  CLEAR_ATTENDANCE: "CLEAR_ATTENDANCE"
};
